website/finance/urls.py
#!/usr/bin/python
# -*- coding: UTF-8 -*-
"""
@file  : urls.py
@Time  : 2020/12/10 9:41
@Author: Tao.Xu
@Email : tao.xu2008@outlook.com
"""

from django.urls import path
# from django.conf.urls import url
from . import views


app_name = 'finance'

urlpatterns = [
    # index page
    path(r'', views.IndexView.as_view(), name='index'),
    path('bank_screws/', views.BankScrewsView.as_view(), name='bank_screws'),
    path('bank_screws/index_valuation', views.BankScrewsIndexValuationView.as_view(), name='bank_screws_index_valuation'),
]


if __name__ == '__main__':
    pass

website/finance/models.py
from django.db import models


# Create your models here.
class BankScrewsIndexValuation(models.Model):
    """Index Valuation Table model"""
    title = models.CharField(max_length=30, verbose_name='标题')
    url = models.CharField(max_length=100, verbose_name='网址')
    content = models.CharField(max_length=200, verbose_name='内容')
    pub_date = models.DateTimeField('Time')  # publish date

    class Meta:
        verbose_name_plural = '爬虫银行螺丝钉'

    def __str__(self):
        return self.title

website/finance/views.py
from django.shortcuts import render
from django.views import generic
from .models import BankScrewsIndexValuation


# Create your views here.
class IndexView(generic.ListView):
    template_name = 'finance/index.html'
    context_object_name = 'info_list'

    def get_queryset(self):
        """get info"""
        return


# ------------- BankScrews View -------------
class BankScrewsView(generic.ListView):
    template_name = 'finance/bank_screws/index.html'
    context_object_name = 'none'

    def get_queryset(self):
        return


class BankScrewsIndexValuationView(generic.ListView):
    template_name = 'finance/bank_screws/index_valuation.html'
    context_object_name = 'index_valuation_list'

    def get_queryset(self):
        return BankScrewsIndexValuation.objects.order_by('title')

website/finance/templates/finance/bank_screws/index.html
{% extends 'home_page/index.html' %}

{% block head %}
  {% load static %}
{% endblock %}

{% block title %}
<title>Build Index Page</title>
{% endblock %}

{% block sidebar %}
    <!-- 侧边栏部分 -->
    <div class="topic-sidebar-wrap">
      <h3 class="space-title kodo">
        <a href="#">定投十年</a>
        <a class="tool folder" arial-value="true" title="" data-toggle="tooltip" data-placement="bottom" data-original-title="展开所有菜单"><i class="fa fa-angle-right"></i></a>
      </h3>
      <div class="doctree">
        <ul><li class="cate-tools branch closed"><a class="node-title category" href="/finance/bank_screws/index_valuation">今日指数估值</a></li></ul>
        <ul><li class="cate-tools branch closed"><a class="node-title category" href="/finance/bank_screws/index_valuation">历史指数估值</a></li></ul>
      </div>
    </div>
{% endblock %}

{% block content %}
    <!-- 正文部分 -->
    <div class="topic-content-wrap">
      <div class="container">
        <div class="article-content">
          <div class="topic-title">
            <div class="doctree">
              <a href="/finance">投资理财</a> &gt; <span>银行螺丝钉</span>
            </div>
            <h2><span>TODO</span></h2>
            <p class="topic-meta">Update：2021-01-28 11:52:03</p>
          </div>

          <div class="topic-detail">
<!--            <p>TODO</p>-->
          </div>
        </div>
      </div>
    </div>
{% endblock %}

website/finance/templates/finance/bank_screws/index_valuation.html
{% extends 'finance/bank_screws/index.html' %}

{% block head %}
  {% load static %}
{% endblock %}

{% block title %}
<title>Builds Branches Page</title>
{% endblock %}

{% block content %}
    <!-- 正文部分 -->
    <div class="topic-content-wrap">
      <div class="container">
        <div class="article-content">
          <div class="topic-title">
            <div class="doctree">
              <a href="/finance">投资理财</a> &gt; <span>银行螺丝钉</span> &gt; <span>Project</span>
            </div>
            <h2><span>to do</span></h2>
            <ul class="object-tools">
              <li>
                <a href="/finance/bank_screws/latest/refresh/" class="addlink">Refresh</a>
              </li>
            </ul>
            <p class="topic-meta">Update：2021-01-28 11:52:03</p>
          </div>

          <div class="topic-detail">
            <table width="100%">
              <thead>
                <tr>
                  <th>Project </th>
                </tr>
              </thead>
              {% if project_list %}
                {% for project in project_list %}
                  <tbody>
                    <tr>
                      <td><a href="{% url 'finance:bank_screws' index_valuation %}"><font size="2">{{ project }}</font></a></td>
                    </tr>
                  </tbody>
                {% endfor %}
              {% endif %}
            </table>
          </div>
        </div>
      </div>
    </div>
{% endblock %}

website/finance/templates/finance/bank_screws/output.html
{% extends 'finance/bank_screws/index.html' %}

{% block head %}
  {% load static %}
{% endblock %}

{% block title %}
<title>Output Page</title>
{% endblock %}

{% block content %}
    <!-- 正文部分 -->
    <div class="topic-content-wrap">
      <div class="container">
        <div class="article-content">
          <div class="topic-title">
            <div class="doctree">
              <a href="/finance">投资理财</a> &gt; <span>银行螺丝钉</span> &gt; <span>Output</span>
            </div>
            <h2><span>Output</span></h2>
            <p class="topic-meta">Update：2021-01-28 11:52:03</p>
          </div>

          <div class="topic-detail">
            {% if output %}
              <p>{{ output }}</p>
            {% endif %}
          </div>
        </div>
      </div>
    </div>
{% endblock %}